version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=fastapi_post_db
      - SECRET_KEY=32db07e92de9ba3f3e7281e12ee1dd13947f4acc3f449aeb876cc7f195aa51a8
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_post_db

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: